#!/bin/bash
usage() {
  echo "Usage: graphene [test [-t <number>]|[-i]] | [-f <file_path>] | -h "
}
if (($# == 0)); then
  python graphene.py
else
  if [ $1 = "test" ]; then
    if (($# == 1)); then
      python test/main.py
      exit 1
    else
      if (($2 == "-i" )); then
        # "Scotty! I need.. more.. isolated tests!"
        python test/main.py -i
        exit 1
      elif (( $2 == "-t" )); then
        if (($# != 3)); then
          usage
          exit 1
        fi
        # "Run this, sesame!"
        python test/main.py -t $3
        exit 1
      else
        usage
        exit 1
      fi
    fi
  fi
  args=" "
  while getopts ":f:t:idh" opt; do
    case $opt in
      f)
        args+=" -f $OPTARG"
        ;;
      
      d)
        # "I don't always know what's going on.. But when I do, I don't!"
        args+=" -d"
        ;;
      h)
        echo "Help is at hand." >&2
        echo "OPTIONS"
        echo -e -n "\t-f"
        echo -e "\tFile to read source from"
        echo -e "\t\tUsage: graphene -f <path>"
        echo -e -n "\n\t-t"
        echo -e "\tRun test Number <number>"
        echo -e "\t\tUsage: graphene test -t <test_name>"
        echo -e -n "\n\t-i"
        echo -e "\tRun tests in isolated mode. One test does not affect another."
        echo -e "\t\tUsage: graphene test -i"
        break
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
      :)
        echo "Option -$OPTARG requires an argument." >&2
        echo "Usage: graphene [test | -t <number> | -i | -f <file_path>] "
        exit 1
        ;;
    esac
  done
  python graphene.py $args
fi