
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '.@*\xad\xec?\xfc\xd8\xf0\xcc\x86G\x1a*i\xa3'
    
_lr_action_items = {'RPAREN':([6,7,],[8,9,]),'STRING':([4,],[6,]),'LPAREN':([2,5,],[4,7,]),'ID':([0,3,],[2,5,]),'DOT':([2,],[3,]),'$end':([1,8,9,],[0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'call':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> call","S'",1,None,None,None),
  ('call -> ID LPAREN STRING RPAREN','call',4,'p_call','graphene.py',41),
  ('call -> ID DOT ID LPAREN RPAREN','call',5,'p_call','graphene.py',42),
]
