
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'k\xef\x1a\xd9!t/\xa0\xd4I\xcbo\x98\xe7(e'
    
_lr_action_items = {'STRING':([3,],[4,]),'RPAREN':([4,],[5,]),'ID':([0,],[2,]),'LPAREN':([2,],[3,]),'$end':([1,5,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'call':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> call","S'",1,None,None,None),
  ('call -> ID LPAREN STRING RPAREN','call',4,'p_call','graphene.py',30),
]
